### ISSUE TITLE
Connect from Raspberry Pi

### ISSUE THREAD

**Issue by blokhin** [WowWeeLabs/CHIP-iOS-SDK#2]
Dear all,

I have got a Raspberry Pi (namely, 3 mod. B) and would like to control two of my CHiPs from there.

It seems, neither iOS SDK, nor Android SDK is not suited for that at all. Please, correct me if I'm wrong. Which options do I have then?

PS i am absolutely fond of CHiP, thanks for your work ❤

**Comment by blokhin** [comment]
Follow-up: since Raspberry is almost normal Unix-PC with the BLE support, controlling CHiP is very easy with the standard Raspbian Bluetooth utilities.

For example, wrapped up in Python using **pexpect**:
```
prompt = '.*\[LE\]>'
bluetooth_service_handle = '0x0018'
child = pexpect.spawn('gatttool -i %s -b %s -I' % (interface, bluetooth_mac_address))
child.expect(prompt, timeout=1)
child.sendline('connect')
child.expect(prompt, timeout=1)
time.sleep(3)
child.sendline('char-write-cmd %s %s' % (bluetooth_service_handle, control_bytes))
```
Unfortunately, `control_bytes` aren't documented at all.

I've figured out some of them are similar to those used in MIP: https://github.com/WowWeeLabs/MiP-BLE-Protocol/blob/master/MiP-Protocol.md

Dear Andy @hongkongkiwi and David @davidchanwww could you please publish the same table of Bluetooth service commands for CHiP? Then hacking CHiP will be more fun ; )

**Comment by adamgreen** [comment]
@blokhin You could check out my [Unofficial CHiP Bluetooth Low Energy Protocol Documentation](https://github.com/adamgreen/CHiP/blob/master/CHiP-BLE-Protocol.md#the-unofficial-chip-bluetooth-low-energy-protocol) and see if it helps. I wrote it to enable the creation of projects like what you are attempting. I would love any feedback you might have.
